spring:
  datasource:
    # URL de conexión a la base de datos H2 en memoria
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: 
  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      # create-drop: Crea las tablas al empezar el test y las borra al terminar
      ddl-auto: create-drop
    # show-sql: Muestra las consultas SQL en la consola (muy útil para depurar)
    show-sql: true
    properties:
      hibernate:
        format_sql: true