name: CI Pipeline MGCSS

on:
  push:
    branches: [ "main", "feature/*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Configurar Java 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Compilar y testear con Maven
      run: mvn clean verify

    - name: Build and analyze
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_CLOUD }}
      run: mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
        -Dsonar.region=us \
        -Dsonar.organization=tinogp \
        -Dsonar.projectKey=Tinogp_mgcss-track-grupo4

